apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "infomesh.fullname" . }}
  labels:
    {{- include "infomesh.labels" . | nindent 4 }}
---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "infomesh.fullname" . }}-data
  labels:
    {{- include "infomesh.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "infomesh.fullname" . }}
  labels:
    {{- include "infomesh.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "infomesh.selectorLabels" . | nindent 6 }}
